{ config, lib, ... }:

{
  # Identity is intentionally set here as a placeholder `mkDefault` - the
  # real values come from ~/.config/workspaces-host/credentials (see
  # README's "Setting up your credentials" section), which
  # `workspaces-host-update` turns into the `programs.git.includes` file
  # below every time it runs. Never edit the values below directly.
  programs.git = {
    enable = true;

    userName = lib.mkDefault "Workspace Engineer";
    userEmail = lib.mkDefault "workspace@example.invalid";

    # A later `[include]` wins over an earlier `[user]` in git's own
    # config cascade, so this - generated by `workspaces-host-update`
    # from the credentials file, never by Nix or by hand - silently
    # overrides the placeholder identity above once it exists, and is
    # silently ignored by git (no error) if it doesn't exist yet.
    includes = [
      { path = "${config.xdg.configHome}/workspaces-host/git-identity"; }
    ];

    extraConfig = {
      init.defaultBranch = "main";
      pull.rebase = true;
      push.autoSetupRemote = true;
      rebase.autoStash = true;
      fetch.prune = true;
      core.editor = "vim";
    };

    # A prettier git diff/show/log -p pager - side-by-side hunks, syntax
    # highlighting, line numbers - with zero learning curve: it's a
    # pager, not a new command to remember.
    delta = {
      enable = true;
      options = {
        navigate = true;
        line-numbers = true;
      };
    };

    aliases = {
      st = "status -sb";
      co = "checkout";
      br = "branch";
      ci = "commit";
      lg = "log --oneline --graph --decorate";
      last = "log -1 HEAD";
    };
  };
}
